#!/usr/bin/env python3
"""
Test if SmartFlow AI responses are actually generated by LLM vs static
"""

import asyncio
import sys
import os
sys.path.append('.')

from app.agents.supervisor_agent import run_supervisor

async def test_ai_generation():
    print('🧪 Testing if AI responses are actually generated by LLM...\n')

    # Test with different questions to see if responses vary
    questions = [
        'Who should I pay first?',
        'What is my cash position?',
        'How is my business doing?'
    ]

    for i, question in enumerate(questions, 1):
        print(f'{i}. Testing: "{question}"')
        print('-' * 50)

        try:
            result = await run_supervisor('test-entity', question)
            response = result.get('output', '')

            # Check if response contains AI-generated elements
            ai_indicators = [
                ('Multi-Agent Analysis' in response, 'Multi-Agent header'),
                ('Top 3 Actions' in response, 'Action recommendations'),
                (len(response) > 200, f'Length: {len(response)} chars'),
                ('₹' in response or '$' in response, 'Currency symbols'),
                ('recommend' in response.lower() or 'suggest' in response.lower(), 'Recommendations')
            ]

            ai_score = sum(1 for indicator, _ in ai_indicators if indicator)

            print(f'✅ AI Generation Score: {ai_score}/5')
            for check, description in ai_indicators:
                status = '✅' if check else '❌'
                print(f'   {status} {description}')

            print(f'📝 Response Preview: {response[:150]}...')
            print()

        except Exception as e:
            print(f'❌ Error: {e}')
            print()

if __name__ == "__main__":
    asyncio.run(test_ai_generation())